### ISSUE TITLE
Error when I import ctcsound in Python 3 on Windows 10

### ISSUE THREAD

**Issue by jamesheston** [csound/ctcsound#16]
I get the error below when I try and `import ctcsound` in a python 3 interactive shell:

```
C:\Users\jjhes>py
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctcsound
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Csound6_x64\bin\ctcsound.py", line 41, in <module>
    libcsound = cdll.csound64
  File "C:\Users\jjhes\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 439, in __getattr__
    dll = self._dlltype(name)
  File "C:\Users\jjhes\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'csound64'. Try using the full path with constructor syntax.
>>>
```

I'm guessing the class syntax is `CDLL(object)` as defined in `jjhes\AppData\...\ctypes\__init__.py`, and the target is `Program Files\Csound6_x64\bin\csound64.dll` but I'm not sure, and I haven't had any luck getting this to run.

Any suggestions? I'm not too experienced with Windows or how wrapping C libraries in Python works.

**Comment by fggp** [comment]
You can type this command from a console; it will display the different
directories in your PYTHONPATH:

      python3 -c "import sys; print('\n'.join(sys.path))"

If the path to C:\Program Files\Csound6_x64\bin isn't there you should
modify/create the system environment variable PYTHONPATH including this
path.

François

Le sam. 7 déc. 2019 à 10:05, James Heston <notifications@github.com> a
écrit :

**Comment by fggp** [comment]
Oh sorry. I read your mail too quickly. In fact it seems that C:\Program
Files\Csound6_x64\bin isn't in your system path. You can test this from the
console with the command:

  echo %PATH%

If this is the case, you should add this path in the system environment
variable PATH

François

**Comment by jamesheston** [comment]
Thanks for the quick response.

`C:\Program Files\Csound6_x64\bin;` does appear to be in my path:
```
C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Csound6_x64\bin;C:\Users\jjhes\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\jjhes\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\jjhes\AppData\Local\Programs\Python\Python38-32\;C:\Users\jjhes\AppData\Local\Microsoft\WindowsApps;C:\Users\jjhes\AppData\Roaming\npm;C:\Users\jjhes\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\jjhes\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Program Files\Docker Toolbox;
```

Also, I am able to import ctcsound in my python2 shell, just not my python3 shell. But the front-end I'm writing is in python3.

**Comment by jamesheston** [comment]
Also, I tried your first suggestion as well, just in case. `py` is the shortcut for python3 on my computer, added by the python executable installer. As you can see from the following output, `C:\Program Files\Csound6_x64\bin` does seem to be in the PYTHONPATH:
```
C:\Users\jjhes>py -c "import sys; print('\n'.join(sys.path))"

C:\Program Files\Csound6_x64\bin
C:\Users\jjhes
C:\Users\jjhes\AppData\Local\Programs\Python\Python38\python38.zip
C:\Users\jjhes\AppData\Local\Programs\Python\Python38\DLLs
C:\Users\jjhes\AppData\Local\Programs\Python\Python38\lib
C:\Users\jjhes\AppData\Local\Programs\Python\Python38
C:\Users\jjhes\AppData\Local\Programs\Python\Python38\lib\site-packages
```

**Comment by fggp** [comment]
It seems that there have been some changes in ctypes with Python 3.8.
Could you try this from a Python 3.8 console and tell me what's happening?
(I don't have a Windows machine here so I can't do the test myself).

import ctypes
pathToLibCsound = ctypes.util.find_library(csound64)
print(pathToLibCsound)
if pathToLibCsound:
    libcsound = ctypes.CDLL(pathToLibCsound)

François

Le dim. 8 déc. 2019 à 06:52, James Heston <notifications@github.com> a
écrit :

**Comment by jamesheston** [comment]
First, I tried:
```
C:\Users\jjhes\Documents\Dev\workbench\little-py-tracker>py
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> pathToLibCsound = ctypes.util.find_library(csound64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ctypes' has no attribute 'util'
>>>
```

Then I tried:
```
C:\Users\jjhes\Documents\Dev\workbench\little-py-tracker>py
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import util
>>> util.find_library(csound64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'csound64' is not defined
```

Also, even though I can import ctcsound in python 2.7, I get the same errors in my python2 shell from running the commands above.

**Comment by fggp** [comment]
That's weird. I will try on my own as soon as I have access to a Windows
machine (maybe tomorrow). Which version of Csound did you install ?

François

Le dim. 8 déc. 2019 à 21:06, James Heston <notifications@github.com> a
écrit :

**Comment by jamesheston** [comment]
--Csound version 6.13 beta (double samples) Jul 12 2019

**Comment by jamesheston** [comment]
I tried uninstalling csound, python 2, and python 3, then reinstalling python 3 and csound and am still getting the same results.

**Comment by fggp** [comment]
I could have a try on a Windows system today. There's effectively an issue
between Python 3.8 and Windows. You can get the corrected ctcsound.py file
here:
https://raw.githubusercontent.com/csound/csound/develop/interfaces/ctcsound.py.
Please let me know if it works on your system.

François

Le lun. 9 déc. 2019 à 09:16, James Heston <notifications@github.com> a
écrit :

**Comment by jamesheston** [comment]
Hourra! It works! Thanks so much!

**Comment by fggp** [comment]
You're welcome. Thanks for testing.

François

Le lun. 9 déc. 2019 à 19:00, James Heston <notifications@github.com> a
écrit :
