### ISSUE TITLE
ctcsound.py packaged with v6.16.2 exceptions on import under OSX

### ISSUE THREAD

**Issue by david-worrall** [csound/ctcsound#20]
- The latest download from https://csound.com/download.html  is v6.16.2
- ctcsound.py packaged with v6.16.2 imports without exception on Windows 10, and appears stable
- On multiple OSX machines ctcsound.py packaged with v6.16.2 exceptions on import.
Here's an example:
>>> Python 3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
import ctcsound
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/CsoundLib64.framework/Resources/Python/Current/ctcsound.py", line 2705, in <module>
    libcspt.NewCsoundPT.restype = ct.c_void_p
  File "/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, NewCsoundPT): symbol not found
>>> 
- Replacing "/Library/Frameworks/CsoundLib64.framework/Resources/Python/Current/ctcsound.py"
with the version released as 6.16.1 as referenced at:
        https://csound.com/site/news/2021/07/11/Csound-6.16
        which refers to version is 6.16.1
does not exception on import on all the OSX machines.

**Comment by fggp** [comment]
Could you try to modify line 2717 in the 6.16.2 version of ctcsound.py, replacing "csnd6.6.0" by "csnd6" and report if it solves your problem?

**Comment by david-worrall** [comment]
HI Francois, Not sure if you got my email, which reported:
There is no "csnd6.6.0" in the ctcsound.py file in question.

However, this DOES fix the problem:

elif sys.platform.startswith('darwin'):
#    libcspt = ct.CDLL(ctypes.util.find_library('csnd6'))    # drw comment
    libcspt = ct.CDLL("libcsnd6.6.0.dylib")                       # replace the above line with this from the earlier version of  ctcsound.py
Cheers, David

**Comment by fggp** [comment]
To be sure: actually is the line libcspt = ct.CDLL("libcsnd6.6.0.dylib")
the correct one?

François

Le ven. 14 janv. 2022 à 11:50, David R Worrall ***@***.***> a
écrit :

**Comment by david-worrall** [comment]
Cher François,
But perhaps that is because I'm using an older version of csound (v 6.15 Aug 10 2020) ? 
[So, I don't have the v 6.16.2 installed - the error was reported by students installing it on their machines - I took their 6.16.2 ctcsound.py and ran it on my  v 6.15, so perhaps that line is different now.] Unfortunately I can't afford to upgrade to a non-working version ATM. The students used the ctcsound.py version from my csound v 6.15 with their v 6.16.2 and it works.
Hope this helps...
David

**Comment by fggp** [comment]
Thanks. I close the issue.

Regards

François

Le ven. 14 janv. 2022 à 12:20, David R Worrall ***@***.***> a
écrit :
